# Generated by Django 5.0.4 on 2024-04-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_index',
            field=models.IntegerField(default=None),
        ),
    ]
