# Generated by Django 5.0.4 on 2024-04-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_task_task_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_index',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
