# Generated by Django 5.0.4 on 2024-04-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_task_task_index'),
    ]

    operations = [
    ]
