# Generated by Django 5.0.4 on 2024-04-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20240413_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_index',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
